development:
  adapter: postgresql
  encoding: unicode
  database: mps_development
  user: vic

production:
  adapter: postgresql
  encoding: unicode
  database: mps_production
  username: ubuntu
  password: 123
